// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('myApp', ['ngResource', 'ui.router']);

  app.config(function($stateProvider) {
    var room1;
    room1 = {
      url: "/Intro",
      templateUrl: "/sceniq/room1.html",
      controller: RoomCtrl
    };
    return $stateProvider.state('room1', room1);
  });

  app.directive('soundButton', function() {
    return {
      restrict: 'E',
      scope: {
        songName: '@',
        id: '@',
        songFile: '@',
        height: '@',
        loop: '='
      },
      controller: function($scope, $resource, $q) {
        var Query, SoundLevel, SoundPlay, SoundStop;
        SoundPlay = $resource('/sounds/play/:id/:loop/:name');
        SoundStop = $resource('/sounds/stop/:id');
        SoundLevel = $resource('/sounds/level/:id/:power');
        Query = $resource('/sounds/query/:id');
        $scope.started = Query.get({
          id: $scope.id
        }, function(res) {
          $scope.playing = res.res;
          if ($scope.playing === true) {
            $scope.classstyle = 'playStyle';
          }
          if ($scope.playing === false) {
            return $scope.classstyle = 'stopStyle';
          }
        });
        $scope.playSong = function() {
          if ($scope.loop === void 0) {
            $scope.loop = false;
          }
          return SoundPlay.get({
            id: $scope.id,
            loop: $scope.loop,
            name: $scope.songFile
          }, function() {});
        };
        $scope.stopSong = function() {
          return SoundStop.get({
            id: $scope.id
          }, function() {});
        };
        $scope.doit = function() {
          if ($scope.playing === false) {
            $scope.playSong();
          }
          if ($scope.playing === true) {
            return $scope.stopSong();
          }
        };
        $scope.level = function() {
          return SoundLevel.get({
            id: $scope.id,
            power: $scope.power
          }, function() {});
        };
        return $scope.started.$promise.then(function() {
          $scope.$on('play', function(sender, evt) {
            if (evt.id !== $scope.id) {
              return;
            }
            $scope.playing = true;
            return $scope.classstyle = 'playStyle';
          });
          return $scope.$on('stop', function(sender, evt) {
            if (evt.id !== $scope.id) {
              return;
            }
            $scope.playing = false;
            return $scope.classstyle = 'stopStyle';
          });
        });
      },
      templateUrl: '/sceniq/soundbutton.html'
    };
  });

  this.RoomCtrl = function($scope, $http, $q, $resource) {
    var Events, Start;
    Events = $resource('/sounds/events');
    Start = $resource('/sounds/starts');
    $scope.getEvent = function() {
      return Events.get({}, function(evt) {
        if (evt.evt === 'play') {
          $scope.$broadcast('play', evt);
        }
        if (evt.evt === 'stop') {
          $scope.$broadcast('stop', evt);
        }
        return $scope.getEvent();
      });
    };
    return $scope.getEvent();
  };

}).call(this);

/*
//@ sourceMappingURL=sceniq.map
*/
